# Generated by Django 5.0 on 2023-12-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_partcipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='descripton',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='partcipants',
            new_name='participants',
        ),
    ]
